
package br.com.malgaxe.estoque.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.malgaxe.com.br/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.malgaxe.estoque.cliente.Itens
     */
    @WebMethod
    @WebResult(name = "itens", targetNamespace = "http://ws.estoque.malgaxe.com.br/", partName = "parameters")
    @Action(input = "http://ws.estoque.malgaxe.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.malgaxe.com.br/EstoqueWS/todosOsItensResponse")
    public Itens todosOsItens(
        @WebParam(name = "listaItem", targetNamespace = "http://ws.estoque.malgaxe.com.br/", partName = "parameters")
        ListaItem parameters);

    /**
     * 
     * @param tokenUsuario
     * @param parameters
     * @return
     *     returns br.com.malgaxe.estoque.cliente.CadastrarItemResponse
     * @throws AutorizacaoFault
     */
    @WebMethod(operationName = "CadastrarItem")
    @WebResult(name = "CadastrarItemResponse", targetNamespace = "http://ws.estoque.malgaxe.com.br/", partName = "result")
    @Action(input = "http://ws.estoque.malgaxe.com.br/EstoqueWS/CadastrarItemRequest", output = "http://ws.estoque.malgaxe.com.br/EstoqueWS/CadastrarItemResponse", fault = {
        @FaultAction(className = AutorizacaoFault.class, value = "http://ws.estoque.malgaxe.com.br/EstoqueWS/CadastrarItem/Fault/AutorizacaoException")
    })
    public CadastrarItemResponse cadastrarItem(
        @WebParam(name = "CadastrarItem", targetNamespace = "http://ws.estoque.malgaxe.com.br/", partName = "parameters")
        CadastrarItem parameters,
        @WebParam(name = "tokenUsuario", targetNamespace = "http://ws.estoque.malgaxe.com.br/", header = true, partName = "tokenUsuario")
        TokenUsuario tokenUsuario)
        throws AutorizacaoFault
    ;

}
